#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DJANGO_USER WITH PASSWORD '$DJANGO_PASSWORD';
    CREATE DATABASE $DJANGO_DATABASE_NAME;
    ALTER ROLE $DJANGO_USER SET client_encoding TO 'utf8';
    ALTER ROLE $DJANGO_USER SET default_transaction_isolation TO 'read committed';
    ALTER ROLE $DJANGO_USER SET timezone TO 'UTC';
    GRANT ALL PRIVILEGES ON DATABASE $DJANGO_DATABASE_NAME TO $DJANGO_USER;
EOSQL
